# Generated by Django 4.1.7 on 2023-04-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_info_bhk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owmer_name', models.CharField(max_length=50)),
                ('garden', models.BooleanField(default=True)),
                ('rent_per_month', models.IntegerField(default=False)),
                ('photos', models.ImageField(default=True, upload_to='media')),
                ('BHK', models.IntegerField(default=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.city')),
            ],
            options={
                'db_table': 'property_rent',
            },
        ),
    ]
