# Generated by Django 4.1.7 on 2023-04-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_rent',
            old_name='owmer_name',
            new_name='Owner_name',
        ),
    ]
