# Generated by Django 4.1.7 on 2023-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_rename_owmer_name_property_rent_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_rent',
            name='video',
            field=models.FileField(default=True, upload_to='media'),
        ),
    ]
