# Generated by Django 4.1.7 on 2023-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_rent_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_rent',
            name='video',
        ),
        migrations.AddField(
            model_name='property_rent',
            name='map',
            field=models.URLField(null=True),
        ),
    ]
