# Generated by Django 4.1.7 on 2023-04-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_rent_video_property_rent_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_rent',
            name='map',
        ),
    ]
